[build-system]
requires = ["setuptools>=67.4.0"]
build-backend = "setuptools.build_meta"

[project]
name="biothings_client"
authors = [
    {name = "Cyrus Afrasiabi"},
    {name = "Xinghua Zhou"},
    {name = "Everaldo Rodolpho", email="erodolpho@scripps.edu"},
    {name = "Chunlei Wu", email = "cwu@scripps.edu"},
]
requires-python = ">=3.8"
description = "Python Client for BioThings API services."
readme = "README.rst"
license = { text = "BSD-3-Clause" }
keywords = [
    "biology", 
    "variant", 
    "gene", 
    "taxon", 
    "species", 
    "drug", 
    "annotation", 
    "web", 
    "service", 
    "client", 
    "api", 
    "myvariant", 
    "mygene"
]
classifiers = [
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: BSD License",
    "Operating System :: POSIX",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Topic :: Utilities",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]
dynamic = ["version"]
dependencies = [
    "httpx>=0.27.2",
    "requests>=2.32.3"
]

[project.optional-dependencies]
dataframe = ["pandas>=0.18.0"]
jsonld = ["PyLD>=0.7.2"]
async = [
    "hishel>=0.0.31",
]
tests = [
    "pytest>=8.3.2",
    "pytest-asyncio>=0.23.8"
]



[project.urls]
homepage = "https://github.com/biothings/biothings_client.py"
repository = "https://github.com/biothings/biothings_client.py"
documentation = "https://biothings-clientpy.readthedocs.io"

[tool.setuptools]
zip-safe = true
# packages = ["biothings_client"]

[tool.setuptools.dynamic]
version = {attr = "biothings_client.__version__"}

[tool.black]
line-length = 120
target-version = ['py38', 'py39', 'py310', 'py311', 'py312']

[tool.isort]
profile = "black"
combine_as_imports = true
line_length = 120
src_paths = ["."]

# pytest configuration
[tool.pytest.ini_options]
minversion = "6.2.5"
pythonpath = ["."]


# Options
addopts = [
    "-rA",
    "-vv",
    "--doctest-modules",
    "--setup-show",
    "--capture=no",
    "--tb=line",
    "--durations=0",
    "--showlocals",
    "--strict-markers",
    "--color=yes",
    "--code-highlight=yes"
]

# Path
norecursedirs = [
    ".svn",
    ".git",
    "_build",
    "tmp*",
    "lib",
    "lib64",
]
testpaths = ["test"]

markers = [
    "unit",
]

# Logging
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s [%(levelname)] %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
